version: '3'

services:
  metacubexd:
    container_name: metacubexd
    image: ghcr.io/metacubex/metacubexd
    restart: always
    ports:
      - '9091:80'

  # optional
  meta:
    container_name: meta
    image: ghcr.io/metacubex/metacubexd
    restart: always
    pid: host
    ipc: host
    network_mode: host
    cap_add:
      - ALL
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./config:/.config/mihomo
